### Import Module

In [85]:
from __future__ import print_function
from __future__ import division

In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

from sklearn.linear_model import LinearRegression

### Dataset

In [87]:
from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [88]:
%cd /content/gdrive/MyDrive/AI Class/Technical/Weight Prediction

/content/gdrive/MyDrive/AI Class/Technical/Weight Prediction


In [89]:
data = pd.read_csv('weight-height.csv')
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [90]:
data.Height.max()

78.9987423463896

In [91]:
data.info

<bound method DataFrame.info of       Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]>

In [92]:
# cek apakah ada null value
data.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [93]:
# cek dimensi dari dataset
data.shape

(10000, 3)

In [94]:
data.iloc[:, 1:]

Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
9995  66.172652  136.777454
9996  67.067155  170.867906
9997  63.867992  128.475319
9998  69.034243  163.852461
9999  61.944246  113.649103

[10000 rows x 2 columns]

In [95]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
label_encoder_gender = LabelEncoder()

data.iloc[:,0] = label_encoder_gender.fit_transform(X[:,0])

In [96]:
data.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [97]:
X = data.iloc[:, :-1].values
print(X)

[[ 1.         73.84701702]
 [ 1.         68.78190405]
 [ 1.         74.11010539]
 ...
 [ 0.         63.86799221]
 [ 0.         69.03424313]
 [ 0.         61.94424588]]


In [98]:
y = data.iloc[:, 2].values
print(y)

[241.89356318 162.31047252 212.74085556 ... 128.47531878 163.85246135
 113.64910268]


### Membagi dataset kedalam training set dan testing set

In [99]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

### Modeling

In [100]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [101]:
from joblib import dump

# Simpan model hasil traning

dump(regressor, "linear-regression.pkl")

['linear-regression.pkl']

In [102]:
# memprediksi test set

y_pred = regressor.predict(X_test)

In [107]:
# testing
X_test.shape

(2000, 2)

In [108]:
X_test

array([[ 1.        , 68.32145287],
       [ 0.        , 64.65471816],
       [ 1.        , 74.03459775],
       ...,
       [ 1.        , 67.55618322],
       [ 0.        , 63.921176  ],
       [ 1.        , 62.41843392]])

In [110]:
data = [[1, 56]]
tes = regressor.predict(data)
tes

array([108.96891748])

### Check Accuracy

In [104]:
y_pred = regressor.predict(X_test)
print('Coefficients      : ', regressor.coef_)

print('Mean Squared Error: %.2f' % np.mean((regressor.predict(X_test)- y_test) ** 2))

print('Variance score    : %.2f' % regressor.score(X_test, y_test))

Coefficients      :  [19.22898618  5.98044901]
Mean Squared Error: 99.84
Variance score    : 0.91


In [105]:
from sklearn.metrics import r2_score,mean_squared_error
r2_score(y_test,y_pred)

0.9062628857795717